### ISSUE TITLE
Icons doesn't appear inside repeater! 

### ISSUE THREAD

**Issue by mustafa-online** [OLSA/FieldtypeFontIcon#1]
Icons doesn't appear **inside repeater**, but works everywhere else!
.
![12556](https://user-images.githubusercontent.com/5323832/45295528-4c9fc780-b4ff-11e8-886a-e60b6a956a9a.PNG)

**Comment by OLSA** [comment]
Hello @Mu9tafa-Online 
sorry for the delayed response, but I don't have that kind of problem and could not replicated (PW 3.0.98, default and Uikit theme). Please can you write what PW version do you use? Also to get icons works inside repeater need to **switch off** option "_repeater dynamically loaded with AJAX in editor_".

**Comment by OLSA** [comment]
Hello @Mu9tafa-Online 
sorry for the delayed response, probably you had that problem with Fontawesome icons because there is conflict with PW core icons (also Fontawesome). Please can you try some other fonticons set (Fontawesome 5, Fontelo etc.)? Here is screenshot where I used Fontelo icons inside repeater.

![icon-in-repeater](https://user-images.githubusercontent.com/2437221/45565142-fa3e0e00-b852-11e8-9417-57c1d684092a.png)
Also as a note, please **switch off** option "Repeater dynamic loading (AJAX)" for repeater field.

**Comment by mustafa-online** [comment]
Great, it works now, thanks. 😍
